/**
 * Regenerates data.js from the Postman collection.
 * Usage: node build.mjs
 *
 * Source of truth: ./postman/EMS_API_postman_collection_v2.json
 * Optional live samples: ./samples.json (from fetch-samples.mjs)
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const COLLECTION = path.resolve(
  __dirname,
  "postman/EMS_API_postman_collection_v2.json"
);
const SAMPLES = path.resolve(__dirname, "samples.json");
const OUT = path.resolve(__dirname, "data.js");

function parseRequired(desc = "") {
  const m = String(desc).match(/^(Yes|No)\s*\|\s*(.*)$/i);
  if (m) {
    return { required: m[1].toLowerCase() === "yes", description: m[2].trim() };
  }
  return { required: null, description: String(desc).trim() };
}

function mapParam(p) {
  const { required, description } = parseRequired(p.description || "");
  return {
    key: p.key,
    value: p.value ?? "",
    description,
    required,
    disabled: !!p.disabled,
  };
}

function walk(items, folder = "") {
  const out = [];
  for (const it of items || []) {
    if (it.item) {
      out.push(...walk(it.item, it.name));
      continue;
    }
    const r = it.request || {};
    const url = r.url || {};
    const body = r.body || {};
    const query = (url.query || []).map(mapParam);
    let bodyParams = [];
    if (body.mode === "urlencoded") {
      bodyParams = (body.urlencoded || []).map(mapParam);
    }
    const examples = (it.response || []).map((ex) => ({
      name: ex.name || "Example",
      status: ex.status || "",
      code: ex.code ?? null,
      body: ex.body || "",
    }));
    out.push({
      id: (it.name || "").replace(/[^\w]+/g, "-").toLowerCase(),
      folder,
      name: it.name,
      method: r.method || "GET",
      path: (url.path || []).join("/"),
      rawUrl: url.raw || "",
      description: r.description || "",
      query,
      bodyMode: body.mode || null,
      bodyParams,
      examples,
      liveSample: null,
    });
  }
  return out;
}

const collection = JSON.parse(fs.readFileSync(COLLECTION, "utf8"));
const endpoints = walk(collection.item);

let samples = {};
if (fs.existsSync(SAMPLES)) {
  samples = JSON.parse(fs.readFileSync(SAMPLES, "utf8"));
  for (const ep of endpoints) {
    if (samples[ep.path]) {
      ep.liveSample = samples[ep.path];
    }
  }
}

const variables = (collection.variable || [])
  .filter((v) => v.key !== "api_key")
  .map((v) => ({
    key: v.key,
    value: v.value || "",
    note:
      v.key === "base_url"
        ? "Production EMS API base"
        : "Set in Postman / your client",
  }));

const data = {
  generatedAt: new Date().toISOString(),
  name: collection.info?.name || "EMS API",
  description: collection.info?.description || "",
  baseUrl: "https://ems.wallan.com/api/v1",
  auth: {
    type: "api_key",
    note:
      "Send api_key in the POST body (recommended) or as ?api_key= query parameter. AI Project key: EMS-AI-B299-X721.",
  },
  officialDocs:
    "https://ems.wallan.com/api/v1/appointment/Documentation.php",
  variables,
  folders: [...new Set(endpoints.map((e) => e.folder))],
  endpoints,
  source: "postman/EMS_API_postman_collection_v2.json",
};

fs.writeFileSync(
  OUT,
  `/* Auto-generated by build.mjs — do not edit by hand. Run: node build.mjs */\nwindow.EMS_DOCS = ${JSON.stringify(data, null, 2)};\n`
);

console.log(
  `Wrote ${OUT} (${endpoints.length} endpoints, ${Object.keys(samples).length} live samples)`
);
